blank_issues_enabled: true
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/otomad/OtomadHelper/discussions/new?category=ideas&labels=suggestion
    about: Suggest ideas for Otomad Helper.
  - name: ğŸ’¬ Question
    url: https://github.com/otomad/OtomadHelper/discussions/new?category=q-a&labels=question
    about: Please ask and answer questions here.
  - name: ğŸ£ Contribute Translations
    url: https://crowdin.com/project/otomadhelper
    about: If you would like to participate in the translation, you are welcome to join as well.
